[DATA]
DATASET = "https://raw.githubusercontent.com/5x12/ml-cookbook/master/supplements/data/heart.csv"

[MODEL]
LOG_REG = "model/conf/logistic_regression.pkl"
SVM = "model/conf/svm.pkl"
SVM_GRID = {'kernel'=['linear', 'rbf']}
LOG_REG_GRID = {'penalty'=['l2', 'none']}

[PREDICTION]
VALUES = [[59, 1, 0, 101, 234, 0, 1, 143, 0, 3.4, 0, 0, 0]]
NUMBER_VALUES = 13